### PR TITLE
Updated workflow to cloud enabled

### PR DESCRIPTION
**Pull request by mcochran-r7**
updated icon file, help.md, yaml file, and screenshots with new workflow information for current plugin versions and cloud-enabled version number.

## Requirements

Workflow contributors, verify you have completed the following items by checking them off:

### Checklist
- [ ] Workflow verified as working in a test
- [ ] Workflow bundle includes `Name_of_Workflow.icon` file, `help.md` file, `workflow.spec.yaml` file, and `screenshots` directory
- [ ] Workflow title should follow general [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Workflow includes a detailed Description
- [ ] Workflow step names follow [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Triggers, Decisions, and other workflow steps include descriptions where needed
- [ ] Workflow includes at least one `Final Report` artifact that summarizes workflow execution details
- [ ] Workflow bundle (directory) is named after the title of the workflow in snake case with first letters capitalized, e.g. `workflows/Name_of_Workflow/`
- [ ] `help.md` file includes Description, Key Features, Requirements, Setup, Technical Details, Version History, and References
- [ ] `workflow.spec.yaml` file includes `products`, `name`, `title`, `description`, `use_cases` tags, `keywords` tags, `source_url`, and the `name` for each screenshot matches a PNG image in the `screenshots` directory

### Assessment

Post your results with screenshots in this PR using the following style:

```
### Screenshots

Screenshots help your reviewers provide valuable feedback on your contribution. To add a screenshot here, simply drag and drop the PNG files from a file explorer.

#### Workflow Builder

<Insert Workflow Image Here>

#### Job

<Insert Job Image Here>

#### Artifact

<Insert Artifact Image Here>
```

### CODE REVIEW

**Review by sengleson-r7 — APPROVED** [review]
Updated Slack steps with some light formatting and a link to the Job. Also reordered screenshots so Slack view is first.

**Review by DHall-R7 — COMMENTED** [review]
The hash lookup for Team Cymru MHR Does not work for Sha256 so the output yields nothing for Team Cymru but does return results for Virus Total. Team Cymru Website supports Sha256. Defect Ticket created to have sha256 included.

**Comment by sengleson-r7** [comment]
@DHall-R7 , does that block releasing this workflow update do you think?

**Comment by DHall-R7** [comment]
> @DHall-R7 , does that block releasing this workflow update do you think?

Sorry Spencer just noticed you wrote a comment back. Not used to Github yet. I don't know if it blocks it or not. I reached out to Natalie about it, and she thought maybe we wait for it to be fixed, but we could also just put notes in the docs page that warn that currently Sha256 will yield no results for that portion of the workflow and to expect empty response. It works with Md5 and Sha1 as expected.

**Review by ewilson-r7 — APPROVED** [review]
Ran through three different indicator test with success.

**Pull request merged**
