### PR TITLE
Update Delete-Emails-from-O365-With-Microsoft-Teams

### PR DESCRIPTION
**Pull request by mcochran-r7**
Update plugin versions, removed python steps, added pattern match arg extraction steps, updated screenshots, updated help and yaml files

## Requirements

Workflow contributors, verify you have completed the following items by checking them off:

### Checklist
- [ ] Workflow verified as working in a test
- [ ] Workflow bundle includes `Name_of_Workflow.icon` file, `help.md` file, `workflow.spec.yaml` file, and `screenshots` directory
- [ ] Workflow title should follow general [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Workflow includes a detailed Description
- [ ] Workflow step names follow [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Triggers, Decisions, and other workflow steps include descriptions where needed
- [ ] Workflow includes at least one `Final Report` artifact that summarizes workflow execution details
- [ ] Workflow bundle (directory) is named after the title of the workflow in snake case with first letters capitalized, e.g. `workflows/Name_of_Workflow/`
- [ ] `help.md` file includes Description, Key Features, Requirements, Setup, Technical Details, Version History, and References
- [ ] `workflow.spec.yaml` file includes `products`, `name`, `title`, `description`, `use_cases` tags, `keywords` tags, `source_url`, and the `name` for each screenshot matches a PNG image in the `screenshots` directory

### Assessment

Post your results with screenshots in this PR using the following style:

```
### Screenshots

Screenshots help your reviewers provide valuable feedback on your contribution. To add a screenshot here, simply drag and drop the PNG files from a file explorer.

#### Workflow Builder

<Insert Workflow Image Here>

#### Job

<Insert Job Image Here>

#### Artifact

<Insert Artifact Image Here>
```

### CODE REVIEW

**Comment by mcochran-r7** [comment]
Working version in Sim Lab https://us.connect.insight.rapid7.com/7F913342E90748B5F07A#/workflows/details/d61bf6bc-0c43-4166-823e-dab4719a2e96/versions/83ce37a2-6ac8-427c-b4cb-943ef3063628

**Comment by DHall-R7** [comment]
The workflow instructions suggest that you can use three different message formats with the workflow:
!find-email user@example.com subject="A phishy email"

!find-email user@example.com subject="A phishy email" delete="True"

!find-email user@example.com subject="A phishy email" from="example.com" body="Click here for free stuff"

Only the last example works to run the workflow successfully. If no from is included it will always take the path of no for "Search Information Found". If this is the desired behavior we can just change the instructions. If we want them to be able to just search by subject and not include a from address then the workflow needs tweaked.

**Comment by mcochran-r7** [comment]
> The workflow instructions suggest that you can use three different message formats with the workflow: !find-email [user@example.com](mailto:user@example.com) subject="A phishy email"
> 
> !find-email [user@example.com](mailto:user@example.com) subject="A phishy email" delete="True"
> 
> !find-email [user@example.com](mailto:user@example.com) subject="A phishy email" from="example.com" body="Click here for free stuff"
> 
> Only the last example works to run the workflow successfully. If no from is included it will always take the path of no for "Search Information Found". If this is the desired behavior we can just change the instructions. If we want them to be able to just search by subject and not include a from address then the workflow needs tweaked.



> The workflow instructions suggest that you can use three different message formats with the workflow: !find-email [user@example.com](mailto:user@example.com) subject="A phishy email"
> 
> !find-email [user@example.com](mailto:user@example.com) subject="A phishy email" delete="True"
> 
> !find-email [user@example.com](mailto:user@example.com) subject="A phishy email" from="example.com" body="Click here for free stuff"
> 
> Only the last example works to run the workflow successfully. If no from is included it will always take the path of no for "Search Information Found". If this is the desired behavior we can just change the instructions. If we want them to be able to just search by subject and not include a from address then the workflow needs tweaked.

Fixed issue changed decision from AND to OR

**Review by DHall-R7 — APPROVED** [review]
Tested workflow without issues. 
Reviewed Yaml and help.md
Pushing changes.

**Pull request merged**
