### PR TITLE
MC-166 - Spearphishing Remediation O365

### PR DESCRIPTION
**Pull request by dmandyna-r7**
## Requirements

Workflow contributors, verify you have completed the following items by checking them off:

### Checklist
- [ ] Workflow verified as working in a test
- [ ] Workflow bundle includes `Name_of_Workflow.icon` file, `help.md` file, `workflow.spec.yaml` file, and `screenshots` directory
- [ ] Workflow title should follow general [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Workflow includes a detailed Description
- [ ] Workflow step names follow [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Triggers, Decisions, and other workflow steps include descriptions where needed
- [ ] Workflow includes at least one `Final Report` artifact that summarizes workflow execution details
- [ ] Workflow bundle (directory) is named after the title of the workflow in snake case with first letters capitalized, e.g. `workflows/Name_of_Workflow/`
- [ ] `help.md` file includes Description, Key Features, Requirements, Setup, Technical Details, Version History, and References
- [ ] `workflow.spec.yaml` file includes `products`, `name`, `title`, `description`, `use_cases` tags, `keywords` tags, `source_url`, and the `name` for each screenshot matches a PNG image in the `screenshots` directory

#### Icon-Validate

<details>

```
[*] Validating workflow at ./Spearphishing_Remediation_with_Office_365/

[*] Running Integration Validators...
[*] Executing validator WorkflowDirectoryNameMatchValidator
[*] Executing validator WorkflowFilesValidator
[*] Executing validator WorkflowHelpValidator
[*] Executing validator WorkflowChangelogValidator
[*] Executing validator WorkflowVendorValidator
[*] Executing validator WorkflowVersionValidator
[*] Executing validator WorkflowExtensionValidator
[*] Executing validator WorkflowSupportValidator
[*] Executing validator WorkflowPNGHashValidator
[*] Executing validator WorkflowICONFileNameValidator
[*] Executing validator WorkflowScreenshotValidator
[*] Executing validator WorkflowTitleValidator
[*] Executing validator WorkflowDescriptionValidator
[*] Executing validator WorkflowNameValidator
[*] Executing validator WorkflowProfanityValidator
[*] Executing validator WorkflowHelpPluginUtilizationValidator
[*] Executing validator WorkflowICONFileValidator
[*] Workflow successfully validated!

----
[*] Total time elapsed: 44.905ms
```

<summary>
icon-validate ./Spearphishing_Remediation_with_Office_365/
</summary>
</details>

### Screenshots

<details>

#### Workflow Builder
workflow1

<summary>
Workflow Builder
</summary>
</details>
<details>

#### Slack Messages
slack1

slack2

<summary>
Slack Messages
</summary>
</details>
<details>

#### Job
job

<summary>
Job
</summary>
</details>
<details>

#### Artifact
artifact

<summary>
Artifact
</summary>
</details>

### CODE REVIEW

**Review by jschipp-r7 — APPROVED** [review]

**Review by jschipp-r7 — CHANGES_REQUESTED** [review]
Let's update the formatting of this message to use bold text instead of markdown headings and base emojis to be current with the other workflows.

Example where this could read better:
Screen Shot 2020-11-04 at 9 36 33 AM


In addition, add this screenshot to the included screenshots in the spec. It shows the users how interactive the workflow is

Screen Shot 2020-11-04 at 9 36 33 AM

**Comment by dmandyna-r7** [comment]
Hey @jschipp-r7,
I've updated the content of the Slack message, here's the current version, let me know if any other changes are required:
slack2

I believe that the other Slack screenshot is already added to the plugin spec:
```
  screenshots:
  - name: workflow1.png
    title: Workflow View
  - name: artifact.png
    title: Successful Remediation Artifact
  - name: slack1.png
    title: Slack Prompt
  - name: slack2.png
    title: Slack Response
  - name: office365_1.png
    title: Office365 Remediation Rule
```

**Review by jschipp-r7 — CHANGES_REQUESTED** [review]
Thanks the updates look good but the investigation URL should be a URL to that investigation's page.

**Comment by dmandyna-r7** [comment]
Thanks Jon, that's corrected now. Here's a new example:
slack2

**Review by jschipp-r7 — APPROVED** [review]

**Pull request merged**
